version: '3'

services:
  db:
    image: postgres:latest
    user: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - mynet

  app:
    build: ./app
    depends_on:
      - db
    networks:
      - mynet

  parser:
    build: ./parser
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - mynet
      
volumes:
  postgres-data:
    driver: local
networks:
  mynet:
